### ISSUE TITLE
Restrictive License

### ISSUE THREAD

**Issue by tmr232** [McGill-DMaS/Kam1n0-Community#2]
Any chance of you changing the license to a free/libre license?
This project looks amazing, but the license makes it almost impossible to use or contribute to.

**Comment by bcmfung** [comment]
Hello,

Yes, we will relax the license after Steven having some publication(s) on
this project.

Thank you.

Regards,
Benjamin

Benjamin Fung ben.fung@mcgill.ca
Canada Research Chair in Data Mining for Cybersecurity
Associate Professor, School of Information Studies
McGill University, Montreal, Canada
http://dmas.lab.mcgill.ca/fung
Tel: 514-3983360

**Comment by tmr232** [comment]
Sounds good :+1: 

Thanks.

**Comment by Manouchehri** [comment]
The noncommercial clause unfortunately makes this project impossible to use for most of us.

**Comment by bcmfung** [comment]
Yes, we understand the issue. We are consulting our Research Office.

**Comment by bcmfung** [comment]
We have relaxed the licensing to:
- Attribution-NonCommercial-ShareAlike 4.0 International ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/))

**Comment by Manouchehri** [comment]
The noncommercial clause still makes it unusable. =(

**Comment by bcmfung** [comment]
According to information received from our Research Office, "NonCommercial" does not prevent you from using Kam1n0 in your company. 

According to [this explanation](http://mollykleinman.com/2008/08/21/cc-howto-2-how-to-use-a-work-with-a-noncommercial-license/), NonCommerical means that "as long as you are not making or trying to make money from your use of the licensed work, you are okay."

Here is the formal definition:
"NonCommercial means not primarily intended for or directed towards commercial advantage or monetary compensation. For purposes of this Public License, the exchange of the Licensed Material for other material subject to Copyright and Similar Rights by digital file-sharing or similar means is NonCommercial provided there is no payment of monetary compensation in connection with the exchange."

**Comment by psifertex** [comment]
Using the software inside a company might very well run afoul of the NonCommercial clause. If you do reverse engineering then using this plugin might very well give you commercial advantage since it makes you better at doing the thing you are paid to do. Wouldn't that count as commercial?

If your intention is to prevent someone else from selling your work, GPL is about the best protection you can get in established free software licenses, though of course it does allow people to sell it, it just means that they can't make changes without also releasing those. You might also consider using trademark protections to prevent some situations where a third party integrates the work. 

A related issue is that Creative Commons isn't for software but for creative expressions. 

In fact, Creative Commons themselves specifically recommends against it: https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

**Comment by Manouchehri** [comment]
Also, even if we are allowed to use it, most people are going to assume
they can't.

Jordan showing up in this thread shows that the industry is probably
interested in the project; if they weren't concerned about the legal issues
of using it, it seems plausible that they might give you some pull requests
in the future.

**Comment by bcmfung** [comment]
Acknowledged. Working on it...

**Comment by bcmfung** [comment]
Further relax to Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)

**Comment by tmr232** [comment]
As mentioned before, CC licenses are a bad choice for code. From their [FAQ](https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions):

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

Seems like GPLv3 would make a good choice, as CC BY-SA 4.0 can be converted to GPLv3. [See here](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3).

**Comment by bcmfung** [comment]
We are changing it to Apache License Version 2.0.

**Comment by tmr232** [comment]
That's awesome!

**Comment by Hamz-a** [comment]
I think this issue can be closed.

**Comment by tmr232** [comment]
True. Closing.
